apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
  labels:
    app: python-backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-backend
  template:
    metadata:
      labels:
        app: python-backend
    spec:
      containers:
      - name: python-backend
        image: aartemdevops10/python-backend:d6ad1dbd7926235cdcdc65684945a388cbf1a1d3
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "50Mi"
            cpu: "64m"
          limits:
            memory: "100Mi"
            cpu: "128m"
