apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-backend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  
    nginx.ingress.kubernetes.io/ssl-terminate-at-proxies: "true"

spec:
  ingressClassName: alb
  rules:
    - host: www.devops10.test-danit.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-backend-service
                port:
                  number: 80
